#!/bin/bash

. .env

make clean build

sam package --output-template-file packaged.yaml \
  --s3-bucket $S3Bucket \
  --s3-prefix $S3KeyPrefix \
  --profile $AWSProfile

sam deploy --template-file packaged.yaml \
  --capabilities CAPABILITY_NAMED_IAM \
  --stack-name $StackName \
  --profile $AWSProfile \
  --parameter-overrides \
    "HostName=$HostName" \
    "TTL=$TTL"


aws cloudformation describe-stacks --stack-name $StackName \
    --output text \
    --profile $AWSProfile
